version: "3.8"
services:
  dpp-postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: dpp_db
      POSTGRES_USER: dpp
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dpp_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - dpp-postgres

volumes:
  dpp_db_data:
